<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-S7EFOJ0I" failures="0" tests="1" name="com.class02.HrmsAssertion" time="0.009" errors="1" timestamp="2020-05-22T12:28:55 EDT" skipped="0">
  <testcase classname="com.class02.HrmsAssertion" name="validLogin" time="0.009">
    <error message="Unresolved compilation problems: 
	The annotation @Test is disallowed for this location
	void[] is an invalid type
	Syntax error on token &quot;addEmployee&quot;, AnnotationName expected after this token
	Illegal modifier for parameter addEmployee; only final is permitted
	Syntax error, insert &quot;[ ]&quot; to complete Dimension
	Syntax error, insert &quot;;&quot; to complete LocalVariableDeclarationStatement
	AddEmployee cannot be resolved to a type
	AddEmployee cannot be resolved to a type
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
The annotation @Test is disallowed for this location
void[] is an invalid type
Syntax error on token "addEmployee", AnnotationName expected after this token
Illegal modifier for parameter addEmployee; only final is permitted
Syntax error, insert "[ ]" to complete Dimension
Syntax error, insert ";" to complete LocalVariableDeclarationStatement
AddEmployee cannot be resolved to a type
AddEmployee cannot be resolved to a type

at com.class02.HrmsAssertion.validLogin(HrmsAssertion.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validLogin -->
  <system-out/>
</testsuite> <!-- com.class02.HrmsAssertion -->
